services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    ports:
      - "3000:3000"
    restart: always
    volumes:
      - ./homepage/config:/app/config
    networks:
      homelab-network:
        ipv4_address: 172.18.0.3
    environment:
      HOMEPAGE_ALLOWED_HOSTS: "homepage.pridebytes.io"
      PUID: ${PUID}
      PGID: ${PGID}

  plex:
    image: plexinc/pms-docker:latest
    container_name: plex
    ports:
      - "32400:32400"
    restart: always
    networks:
      homelab-network:
        ipv4_address: 172.18.0.2
    environment:
      - TZ=America/Denver  # Set your timezone
    volumes:
      - ./plex/config:/config
      - ./plex/data:/data
      - ./plex/media:/media

networks:
  homelab-network:
    driver: bridge
    ipam:
      config:
        - subnet: "172.18.0.0/16"
